version: '2.1'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    networks: 
      - app-tier
    ports:
      - '2181:2181'
      - '3888:3888'
      - '2888:2888'
    expose:
      - '2128'
      - '3888'
      - '2888'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper-server
  kafka:
    image: bitnami/kafka:latest
    networks: 
      - app-tier
    ports:
      - '9092:9092'
    expose:
      - '9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    container_name: kafka-server
  python-client:
    stdin_open: true
    tty: true
    networks:
      - app-tier
    image: kennethreitz/pipenv
    container_name: python-client


networks:
  app-tier:
    name: kafka-pack
    driver: bridge