version: '2.1'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    networks: 
      - app-tier
    ports:
      - '2181:2181'
      - '3888:3888'
      - '2888:2888'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper-server

  kafka:
    image: bitnami/kafka:latest
    networks: 
      - app-tier
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    container_name: kafka-server

  python-client:
    stdin_open: true
    tty: true
    networks:
      - app-tier
    image: kennethreitz/pipenv
    environment:
      - KAFKA_HOST=kafka:9092
    container_name: python-client

  spark-client:
    stdin_open: true
    tty: true
    networks:
      - app-tier
    image: milktea736/spark-kafka
    environment:
      - ZOOKEEPER_HOST=zookeeper:2181
    container_name: spark-client


networks:
  app-tier:
    name: kafka-pack
    driver: bridge